### ISSUE TITLE
fun. will try it.

### ISSUE THREAD

**Issue by khanh2003** [zeke/an-array-of-english-words#2]

**Comment by zeke** [comment]
Cool! Let me know what you make with it.

**Comment by khanh2003** [comment]
I made thelistenheargame.ml
Look at the source code!

Vào 07-07-2016 00:24, "Zeke Sikelianos" <notifications@github.com> đã viết:

**Comment by zeke** [comment]
Cool!

Feedback:

- repeat the word automatically every second or two
- show visual feedback when my guess is wrong

Are you storing the user input somewhere? That could be interesting. I typed 'weak', then 'week'. Could be a good way to find homonyms and stuff.
